contact/urls.py
from django.urls import path
from . import views
app_name = "contact"

urlpatterns = [
    path('', views.contact, name="contact")
]

login/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name='index'),
]

myweb/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name="about"),
    path('service/', views.service, name="service"),
    path('contact/', include('contact.urls', namespace="contact")),
    path('admin/', admin.site.urls),
]

contact/models.py
from django.db import models

# Create your models here.
class ContactModel(models.Model):
    nama_lengkap        = models.CharField(max_length=200)
    email               = models.CharField(max_length=200)
    subject             = models.CharField(max_length=250)
    message             = models.TextField()


    def __str__(self):
        return"{}.{}".format(self.id, self.nama_lengkap)

login/models.py
from django.db import models

# Create your models here.

contact/forms.py
from django import forms
from .models import ContactModel


class ContactForm(forms.ModelForm):
    class Meta:
        model   = ContactModel
        fields   = [
            'nama_lengkap',
            'email',
            'subject',
            'message',
        ]


# class ContactForm(forms.Form):
#     nama_lengkap        = forms.CharField(max_length=200)
#     email               = forms.CharField(max_length=200)
#     subject             = forms.CharField(max_length=250)
#     message             = forms.CharField(max_length=250, widget=forms.Textarea)

login/forms.py
from django import forms

class feedbackForm(forms,form):
    name = forms.CharField(max_length=100)
    email = forms.EmailField()
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)

contact/views.py
from django.shortcuts import render
from .models import ContactModel
from .forms import ContactForm


# Create your views here.

def contact(request):
    models = ContactModel.objects.all()
    form = ContactForm(request.POST or None)
    context = {
        'form': form,
        'model': models,
    }

    if request.method == 'POST':
        if form.is_valid():
            form.save()

            # ContactModel.objects.create(
            #             nama_lengkap      = request.POST.get('nama_lengkap'),
            #             email             = request.POST.get('email'),
            #             subject          = request.POST.get('subject'),
            #             message           = request.POST.get('message'),
            # )




    return  render(request, 'contact/contact.html', context)

login/views.py
from django.shortcuts import render


# Create your views here.
def index

myweb/views.py
from django.shortcuts import render

def index(request):
    return  render(request, 'index.html')

def about(request):
    return  render(request, 'about.html')

def service(request):
    return  render(request, 'service.html')

def contact(request):
    return  render(request, 'contact.html')

contact/templates/contact/contact.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>contact</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Barlow:wght@500;600;700&family=Open+Sans:wght@400;600&display=swap" rel="stylesheet"> 

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<div>
    <!-- Topbar Start -->
    <div class="container-fluid bg-secondary ps-5 pe-0 d-none d-lg-block">
        <!-- <div class="row gx-0">
            <div class="col-md-6 text-center text-lg-start mb-2 mb-lg-0">
                <div class="d-inline-flex align-items-center">
                    <a class="text-body py-2 pe-3 border-end" href=""><small>FAQs</small></a>
                    <a class="text-body py-2 px-3 border-end" href=""><small>Support</small></a>
                    <a class="text-body py-2 px-3 border-end" href=""><small>Privacy</small></a>
                    <a class="text-body py-2 px-3 border-end" href=""><small>Policy</small></a>
                    <a class="text-body py-2 ps-3" href=""><small>Career</small></a>
                </div> -->
            <!-- </div> -->
            <div class="col-md-6 text-center text-lg-end">
                <div class="position-relative d-inline-flex align-items-center bg-primary text-white top-shape px-5">
                    <div class="me-3 pe-3 border-end py-2">
                        <p class="m-0"><i class="fa fa-envelope-open me-2"></i>zhaputralyadi@gmail.com</p>
                    </div>
                    <div class="py-2">
                        <p class="m-0"><i class="fa fa-phone-alt me-2"></i>+6283850297509</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Topbar End -->


    <!-- Navbar Start -->
    <nav class="navbar navbar-expand-lg bg-white navbar-light shadow-sm px-5 py-3 py-lg-0">
        
            <h1 class="m-0 text-uppercase text-primary"><i class="far fa-user text-primary me-2"></i>LYADI ZHAPUTRA</h1>
        
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav ms-auto py-0 me-n3">
                <a href="{% url 'index' %}" class="nav-item nav-link">Home</a>
                <a href="{% url 'about' %}" class="nav-item nav-link">About</a>
                <a href="{% url 'service' %}" class="nav-item nav-link">Service</a>
                <!-- <div class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>
                    <div class="dropdown-menu m-0">
                        <a href="blog.html" class="dropdown-item">Blog Grid</a>
                        <a href="detail.html" class="dropdown-item">Blog Detail</a>
                        <a href="feature.html" class="dropdown-item">Features</a>
                        <a href="quote.html" class="dropdown-item">Quote Form</a>
                        <a href="team.html" class="dropdown-item">The Team</a>
                        <a href="testimonial.html" class="dropdown-item">Testimonial</a>
                    </div>
                </div> -->
                <a href="{% url 'contact:contact' %}" class="nav-item nav-link active">Contact</a>
            </div>
        </div>
    </nav>
    <!-- Navbar End -->


    <!-- Page Header Start -->
    <div class="container-fluid bg-dark p-5">
        <div class="row">
            <div class="col-12 text-center">
                <h1 class="display-4 text-white">Contact me</h1>
                <!-- <a href="">Home</a>
                <i class="far fa-square text-primary px-2"></i>
                <a href="">Contact</a> -->
            </div>
        </div>
    </div>
    <!-- Page Header End -->


    <!-- Contact Start -->
    <div class="container-fluid bg-secondary px-0">
        <div class="row g-0">
            <div class="col-lg-6 py-6 px-5">
                <h1 class="display-5 mb-4">Contact For Any Queries</h1>
                 <form method="post">
                    {% csrf_token %}
                    <!-- {% csrf_token %} -->
                    <div class="row g-3">
                        <div class="col-6">
                            <div class="form-floating">
                                
                                <input type="text" name="nama_lengkap" class="form-control" id="nama_lengkap placeholder="John Doe">
                                <label for="nama_lengkap">{{ form.nama_lengkap.label_tag }}</label>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="form-floating">
                                
                                <input type="text" name="email" class="form-control" id="email" placeholder="name@example.com">
                                <label for="email">{{ form.email.label_tag }}</label>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="form-floating">
                                
                                <input type="text" name="subject" class="form-control" id="subject" placeholder="Subject">
                                <label for="subject">{{ form.subject.label_tag }}</label>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="form-floating">
                                
                                <textarea class="form-control" name="message" placeholder="Message" id="message" style="height: 150px"></textarea>
                                <label for="message">{{ form.message.label_tag }}</label>
                              </div>
                        </div>
                        <div class="col-12">
                            <button class="btn btn-primary w-100 py-3" type="submit" value="send Feedback">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-lg-6" style="min-height: 400px;">
                <div class="position-relative h-100">
                    <iframe class="position-relative w-100 h-100"
                        src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d126710.14865125078!2d113.40734395753421!3d-7.045417238717318!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2dd9d1607b53f50d%3A0x4027a76e3cd9df0!2sPegantenan%2C%20Pamekasan%20Regency%2C%20East%20Java!5e0!3m2!1sen!2sid!4v1671768779463!5m2!1sen!2sid"
                        frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
                </div>
            </div>
        </div>
    </div>
    <!-- Contact End -->


    <!-- Footer Start -->
    <div class="container-fluid bg-primary text-secondary p-5">
        <div class="row g-5">
            <div class="col-12 text-center">
                <h1 class="display-5 mb-4">Stay Update!!!</h1>
                <form class="mx-auto" style="max-width: 600px;">
                    <div class="input-group">
                        <input type="text" class="form-control border-white p-3" placeholder="Your Email">
                        <button class="btn btn-dark px-4">Sign Up</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="container-fluid bg-dark text-secondary p-5">
        <div class="row g-5">
            <!-- <div class="col-lg-3 col-md-6">
                <h3 class="text-white mb-4">Quick Links</h3>
                <div class="d-flex flex-column justify-content-start">
                    <a class="text-secondary mb-2" href="#"><i class="bi bi-arrow-right text-primary me-2"></i>Home</a>
                    <a class="text-secondary mb-2" href="#"><i class="bi bi-arrow-right text-primary me-2"></i>About Us</a>
                    <a class="text-secondary mb-2" href="#"><i class="bi bi-arrow-right text-primary me-2"></i>Our Services</a>
                    <a class="text-secondary mb-2" href="#"><i class="bi bi-arrow-right text-primary me-2"></i>Latest Blog Post</a>
                    <a class="text-secondary" href="#"><i class="bi bi-arrow-right text-primary me-2"></i>Contact Us</a>
                </div>
            </div> -->
            <!-- <div class="col-lg-3 col-md-6">
                <h3 class="text-white mb-4">Popular Links</h3>
                <div class="d-flex flex-column justify-content-start">
                    <a class="text-secondary mb-2" href="#"><i class="bi bi-arrow-right text-primary me-2"></i>Home</a>
                    <a class="text-secondary mb-2" href="#"><i class="bi bi-arrow-right text-primary me-2"></i>About Us</a>
                    <a class="text-secondary mb-2" href="#"><i class="bi bi-arrow-right text-primary me-2"></i>Our Services</a>
                    <a class="text-secondary mb-2" href="#"><i class="bi bi-arrow-right text-primary me-2"></i>Latest Blog Post</a>
                    <a class="text-secondary" href="#"><i class="bi bi-arrow-right text-primary me-2"></i>Contact Us</a>
                </div>
            </div> -->
            <div class="col-lg-3 col-md-6">
                <h3 class="text-white mb-4">Get In Touch</h3>
                <p class="mb-2"><i class="bi bi-geo-alt text-primary me-2"></i>pegantenan,pamekasan,indonesia</p>
                <p class="mb-2"><i class="bi bi-envelope-open text-primary me-2"></i>zhaputralyadi@gmail.com</p>
                <p class="mb-0"><i class="bi bi-telephone text-primary me-2"></i>+6283850297509</p>
            </div>
            <div class="col-lg-3 col-md-6">
                <h3 class="text-white mb-4">Follow me</h3>
                <div class="d-flex">
                    <a class="btn btn-lg btn-primary btn-lg-square rounded-circle me-2" href="https://twiter.com/OfficialYadyy?t=Hptj2KqbP3p20sQL6RzjEw&s=08"><i class="fab fa-twitter fw-normal"></i></a>
                    <a class="btn btn-lg btn-primary btn-lg-square rounded-circle me-2" href="https://www.facebook.com/mufa.bhawellznamtiga"><i class="fab fa-facebook-f fw-normal"></i></a>
                    <a class="btn btn-lg btn-primary btn-lg-square rounded-circle me-2" href="https://www.whatsapp.com/wa.me/+6283850297509"><i class="fab fa-whatsapp fw-normal"></i></a>
                    <a class="btn btn-lg btn-primary btn-lg-square rounded-circle" href="https://instagram.com/yadi_zhaoutra?igshid=YmMyMTA2M2Y="><i class="fab fa-instagram fw-normal"></i></a>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid bg-dark text-secondary text-center border-top py-4 px-5" style="border-color: rgba(256, 256, 256, .1) !important;">
        <p class="m-0">&copy; <a class="text-secondary border-bottom" href="#">lyadi zhaputra</a>. All Rights Reserved 2022. Designed by mulyadi <a class="text-secondary border-bottom"></a></p>
    </div>
    <!-- Footer End -->


    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square rounded-circle back-to-top"><i class="bi bi-arrow-up"></i></a>


    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="lib/easing/easing.min.js"></script>
    <script src="lib/waypoints/waypoints.min.js"></script>
    <script src="lib/owlcarousel/owl.carousel.min.js"></script>

    <!-- Template Javascript -->
    <script src="js/main.js"></script>
</body>

</html>

templates/about.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>about</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->
    <link href="{% static 'img/favicon.ico' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Barlow:wght@500;600;700&family=Open+Sans:wght@400;600&display=swap" rel="stylesheet"> 

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<div>
    <!-- Topbar Start -->
    <!-- <div class="container-fluid bg-secondary ps-5 pe-0 d-none d-lg-block">
        <div class="row gx-0">
            <div class="col-md-6 text-center text-lg-start mb-2 mb-lg-0">
                <div class="d-inline-flex align-items-center">
                    <a class="text-body py-2 pe-3 border-end" href=""><small>FAQs</small></a>
                    <a class="text-body py-2 px-3 border-end" href=""><small>Support</small></a>
                    <a class="text-body py-2 px-3 border-end" href=""><small>Privacy</small></a>
                    <a class="text-body py-2 px-3 border-end" href=""><small>Policy</small></a>
                    <a class="text-body py-2 ps-3" href=""><small>Career</small></a>
                </div>
            </div> -->
            <div class="col-md-6 text-center text-lg-end">
                <div class="position-relative d-inline-flex align-items-center bg-primary text-white top-shape px-5">
                    <div class="me-3 pe-3 border-end py-2">
                        <p class="m-0"><i class="fa fa-envelope-open me-2"></i>zhaputralyadi@gmail.com</p>
                    </div>
                    <div class="py-2">
                        <p class="m-0"><i class="fa fa-phone-alt me-2"></i>+6283850297509</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Topbar End -->


    <!-- Navbar Start -->
    <nav class="navbar navbar-expand-lg bg-white navbar-light shadow-sm px-5 py-3 py-lg-0">
        
            <h1 class="m-0 text-uppercase text-primary"><i class="far fa-user text-primary me-2"></i>LYADI ZHAPUTRA</h1>
        
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav ms-auto py-0 me-n3">
                <a href="{% url 'index' %}" class="nav-item nav-link">Home</a>
                <a href="{% url 'about' %}" class="nav-item nav-link active">About</a>
                <a href="{% url 'service' %}" class="nav-item nav-link">Service</a>
                <!-- <div class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>
                    <div class="dropdown-menu m-0">
                        <a href="blog.html" class="dropdown-item">Blog Grid</a>
                        <a href="detail.html" class="dropdown-item">Blog Detail</a>
                        <a href="feature.html" class="dropdown-item">Features</a>
                        <a href="quote.html" class="dropdown-item">Quote Form</a>
                        <a href="team.html" class="dropdown-item">The Team</a>
                        <a href="testimonial.html" class="dropdown-item">Testimonial</a>
                    </div>
                </div> -->
                <a href="{% url 'contact:contact' %}" class="nav-item nav-link">Contact</a>
            </div>
        </div>
    </nav>
    <!-- Navbar End -->


    <!-- Page Header Start -->
    <div class="container-fluid bg-dark p-5">
        <div class="row">
            <div class="col-12 text-center">
                <h1 class="display-4 text-white">About me</h1>
                <!-- <a href="">Home</a>
                <i class="far fa-square text-primary px-2"></i>
                <a href="">About</a> -->
            </div>
        </div>
    </div>
    <!-- Page Header End -->


    <!-- About Start -->
    <div class="container-fluid bg-secondary p-0">
        <div class="row g-0">
            <div class="col-lg-6 py-6 px-5">
                <h1 class="display-5 mb-4"><span class="text-primary">MULYADI</span></h1>
                <h4 class="text-primary mb-4">nama saya mulyadi,biasa di pangil mol atau yadi,saya lahir di pamekasan pada 21 0ktober 2001,dan saya tinggal di desa ambender kecamatan pegantenan pamekasan,dan di besarkan oleh ibu saya musrifah </h4>
                <p class="mb-4">saya menempuh pendidikan saya di TK rafiq EL-khaeriyah,seoklah dasar di MI tarbiyatul islami,sekolah menengah pertama saya di smp nurul mustofa,Sekolah menengah kejuruan saya di smk nurul mustofa,dan saat ini saya sedang menempuh perguruan tinggi di salah satu kampus di pamekasab yaitu Universitas islam madura.</p>
                <a href="" class="btn btn-primary py-md-3 px-md-5 rounded-pill">Get A Quote</a>
            </div>
            <div class="col-lg-6">
                <div class="h-100 d-flex flex-column justify-content-center bg-primary p-5">
                    <div class="d-flex text-white mb-5">
                        <div class="d-flex flex-shrink-0 align-items-center justify-content-center bg-white text-primary rounded-circle mx-auto mb-4" style="width: 60px; height: 60px;">
                            <i class="fa fa-user-tie fs-4"></i>
                        </div>
                        <div class="ps-4">
                            <h3>hobi</h3>
                            <p class="mb-0">bermain game online,seperti mobile legend,clans of clan,pubg,free fire,dan olahraga seperti sepak bola,futsal,tennis meja,untuk tetamp menjaga kebugaraan tubuh saya biasa joging selama 30 menit.</p>
                        </div>
                    </div>
                    <div class="d-flex text-white mb-5">
                        <div class="d-flex flex-shrink-0 align-items-center justify-content-center bg-white text-primary rounded-circle mx-auto mb-4" style="width: 60px; height: 60px;">
                            <i class="fa fa-chart-line fs-4"></i>
                        </div>
                        <div class="ps-4">
                            <h3>pencapaian</h3>
                            <p class="mb-0">sampai saat ini sata belum tau pasti pencapaian seperti apa yang sudah saya raih,namun saya tetap bersykur karna masih bisa melihat dunia.</p>
                        </div>
                    </div>
                    <div class="d-flex text-white">
                        <div class="d-flex flex-shrink-0 align-items-center justify-content-center bg-white text-primary rounded-circle mx-auto mb-4" style="width: 60px; height: 60px;">
                            <i class="fa fa-balance-scale fs-4"></i>
                        </div>
                        <div class="ps-4">
                            <h3>target</h3>
                            <p class="mb-0">ingin bisa istiqomah beribadah,tidak toxic,lebih percaya diri,lebih konsisten,untuk mencapai cita cita dan  membahagiakan orang tua </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- About End -->


    <!-- Team Start -->
    <div class="container-fluid py-6 px-5">
        <div class="text-center mx-auto mb-5" style="max-width: 600px;">
            <h1 class="display-5 mb-0">my family</h1>
            <hr class="w-25 mx-auto bg-primary">
        </div>
        <div class="row g-5">
            <div class="col-lg-4">
                <div class="team-item position-relative overflow-hidden">
                    <img class="img-fluid w-100" src="{% static 'img/team-1.jpg' %}" alt="">
                    <div class="team-text w-100 position-absolute top-50 text-center bg-primary p-4">
                        <h3 class="text-white">abdul qodir</h3>
                        <p class="text-white text-uppercase mb-0">sampang</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="team-item position-relative overflow-hidden">
                    <img class="img-fluid w-100" src="{% static 'img/team-2.jpg' %}" alt="">
                    <div class="team-text w-100 position-absolute top-50 text-center bg-primary p-4">
                        <h3 class="text-white">Mulyadi</h3>
                        <p class="text-white text-uppercase mb-0">pamekasan</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="team-item position-relative overflow-hidden">
                    <img class="img-fluid w-100" src="{% static 'img/team-3.jpg' %}" alt="">
                    <div class="team-text w-100 position-absolute top-50 text-center bg-primary p-4">
                        <h3 class="text-white">musrifah</h3>
                        <p class="text-white text-uppercase mb-0">pamekasan</p>
                    </div>
                </div>
            </div>
        </div>
    </div>  
   
</body>

</html>